onejar: DeployPackagedVersion
main: org.litesoft.deploypackagedversion.DeployPackagedVersion

resources: 
- LICENSE

dependencies:
- ../LiteSoftAWS
- ../PackagedVersionCommonWithAWS

classpath:
- ../LiteSoftServerUtils/libs|**.jar
- ../LiteSoftAWS/libs|**.jar

